// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: proto/webrtc/webrtc.proto

package webrtc

import (
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RoomParticipants struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string               `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Username string               `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	JoinedAt *timestamp.Timestamp `protobuf:"bytes,3,opt,name=JoinedAt,proto3" json:"JoinedAt,omitempty"`
	LeaveAt  *timestamp.Timestamp `protobuf:"bytes,4,opt,name=LeaveAt,proto3" json:"LeaveAt,omitempty"`
}

func (x *RoomParticipants) Reset() {
	*x = RoomParticipants{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_webrtc_webrtc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomParticipants) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomParticipants) ProtoMessage() {}

func (x *RoomParticipants) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webrtc_webrtc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomParticipants.ProtoReflect.Descriptor instead.
func (*RoomParticipants) Descriptor() ([]byte, []int) {
	return file_proto_webrtc_webrtc_proto_rawDescGZIP(), []int{0}
}

func (x *RoomParticipants) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RoomParticipants) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RoomParticipants) GetJoinedAt() *timestamp.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

func (x *RoomParticipants) GetLeaveAt() *timestamp.Timestamp {
	if x != nil {
		return x.LeaveAt
	}
	return nil
}

type RoomDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelId    string              `protobuf:"bytes,1,opt,name=ChannelId,proto3" json:"ChannelId,omitempty"`
	Participants []*RoomParticipants `protobuf:"bytes,2,rep,name=Participants,proto3" json:"Participants,omitempty"`
}

func (x *RoomDetails) Reset() {
	*x = RoomDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_webrtc_webrtc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomDetails) ProtoMessage() {}

func (x *RoomDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webrtc_webrtc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomDetails.ProtoReflect.Descriptor instead.
func (*RoomDetails) Descriptor() ([]byte, []int) {
	return file_proto_webrtc_webrtc_proto_rawDescGZIP(), []int{1}
}

func (x *RoomDetails) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *RoomDetails) GetParticipants() []*RoomParticipants {
	if x != nil {
		return x.Participants
	}
	return nil
}

type Room struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string               `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Details  *RoomDetails         `protobuf:"bytes,2,opt,name=Details,proto3" json:"Details,omitempty"`
	OpenedAt *timestamp.Timestamp `protobuf:"bytes,3,opt,name=OpenedAt,proto3" json:"OpenedAt,omitempty"`
	ClosedAt *timestamp.Timestamp `protobuf:"bytes,4,opt,name=ClosedAt,proto3" json:"ClosedAt,omitempty"`
}

func (x *Room) Reset() {
	*x = Room{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_webrtc_webrtc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webrtc_webrtc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_proto_webrtc_webrtc_proto_rawDescGZIP(), []int{2}
}

func (x *Room) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Room) GetDetails() *RoomDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *Room) GetOpenedAt() *timestamp.Timestamp {
	if x != nil {
		return x.OpenedAt
	}
	return nil
}

func (x *Room) GetClosedAt() *timestamp.Timestamp {
	if x != nil {
		return x.ClosedAt
	}
	return nil
}

type CreateRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelId string `protobuf:"bytes,1,opt,name=ChannelId,proto3" json:"ChannelId,omitempty"`
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_webrtc_webrtc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webrtc_webrtc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_webrtc_webrtc_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRoomRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type GetRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *GetRoomRequest) Reset() {
	*x = GetRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_webrtc_webrtc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomRequest) ProtoMessage() {}

func (x *GetRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webrtc_webrtc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomRequest.ProtoReflect.Descriptor instead.
func (*GetRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_webrtc_webrtc_proto_rawDescGZIP(), []int{4}
}

func (x *GetRoomRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_proto_webrtc_webrtc_proto protoreflect.FileDescriptor

var file_proto_webrtc_webrtc_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x65, 0x62, 0x72, 0x74, 0x63, 0x2f, 0x77,
	0x65, 0x62, 0x72, 0x74, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x77, 0x65, 0x62,
	0x72, 0x74, 0x63, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb4, 0x01, 0x0a, 0x10, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x61, 0x72,
	0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x36, 0x0a,
	0x08, 0x4a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x4a, 0x6f, 0x69,
	0x6e, 0x65, 0x64, 0x41, 0x74, 0x12, 0x34, 0x0a, 0x07, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x41, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x07, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x41, 0x74, 0x22, 0x69, 0x0a, 0x0b, 0x52,
	0x6f, 0x6f, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x3c, 0x0a, 0x0c, 0x50, 0x61, 0x72, 0x74,
	0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x77, 0x65, 0x62, 0x72, 0x74, 0x63, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x61, 0x72, 0x74,
	0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x73, 0x52, 0x0c, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63,
	0x69, 0x70, 0x61, 0x6e, 0x74, 0x73, 0x22, 0xb5, 0x01, 0x0a, 0x04, 0x52, 0x6f, 0x6f, 0x6d, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12,
	0x2d, 0x0a, 0x07, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x77, 0x65, 0x62, 0x72, 0x74, 0x63, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x07, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x36,
	0x0a, 0x08, 0x4f, 0x70, 0x65, 0x6e, 0x65, 0x64, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x4f, 0x70,
	0x65, 0x6e, 0x65, 0x64, 0x41, 0x74, 0x12, 0x36, 0x0a, 0x08, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64,
	0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x41, 0x74, 0x22, 0x31,
	0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49,
	0x64, 0x22, 0x20, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x49, 0x64, 0x32, 0x6b, 0x0a, 0x05, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x12, 0x33, 0x0a, 0x06,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x77, 0x65, 0x62, 0x72, 0x74, 0x63, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0c, 0x2e, 0x77, 0x65, 0x62, 0x72, 0x74, 0x63, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x22,
	0x00, 0x12, 0x2d, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x16, 0x2e, 0x77, 0x65, 0x62, 0x72, 0x74,
	0x63, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0c, 0x2e, 0x77, 0x65, 0x62, 0x72, 0x74, 0x63, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x22, 0x00,
	0x42, 0x0e, 0x5a, 0x0c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x65, 0x62, 0x72, 0x74, 0x63,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_webrtc_webrtc_proto_rawDescOnce sync.Once
	file_proto_webrtc_webrtc_proto_rawDescData = file_proto_webrtc_webrtc_proto_rawDesc
)

func file_proto_webrtc_webrtc_proto_rawDescGZIP() []byte {
	file_proto_webrtc_webrtc_proto_rawDescOnce.Do(func() {
		file_proto_webrtc_webrtc_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_webrtc_webrtc_proto_rawDescData)
	})
	return file_proto_webrtc_webrtc_proto_rawDescData
}

var file_proto_webrtc_webrtc_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_webrtc_webrtc_proto_goTypes = []interface{}{
	(*RoomParticipants)(nil),    // 0: webrtc.RoomParticipants
	(*RoomDetails)(nil),         // 1: webrtc.RoomDetails
	(*Room)(nil),                // 2: webrtc.Room
	(*CreateRoomRequest)(nil),   // 3: webrtc.CreateRoomRequest
	(*GetRoomRequest)(nil),      // 4: webrtc.GetRoomRequest
	(*timestamp.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_proto_webrtc_webrtc_proto_depIdxs = []int32{
	5, // 0: webrtc.RoomParticipants.JoinedAt:type_name -> google.protobuf.Timestamp
	5, // 1: webrtc.RoomParticipants.LeaveAt:type_name -> google.protobuf.Timestamp
	0, // 2: webrtc.RoomDetails.Participants:type_name -> webrtc.RoomParticipants
	1, // 3: webrtc.Room.Details:type_name -> webrtc.RoomDetails
	5, // 4: webrtc.Room.OpenedAt:type_name -> google.protobuf.Timestamp
	5, // 5: webrtc.Room.ClosedAt:type_name -> google.protobuf.Timestamp
	3, // 6: webrtc.Rooms.Create:input_type -> webrtc.CreateRoomRequest
	4, // 7: webrtc.Rooms.Get:input_type -> webrtc.GetRoomRequest
	2, // 8: webrtc.Rooms.Create:output_type -> webrtc.Room
	2, // 9: webrtc.Rooms.Get:output_type -> webrtc.Room
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_webrtc_webrtc_proto_init() }
func file_proto_webrtc_webrtc_proto_init() {
	if File_proto_webrtc_webrtc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_webrtc_webrtc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomParticipants); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_webrtc_webrtc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_webrtc_webrtc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Room); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_webrtc_webrtc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_webrtc_webrtc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_webrtc_webrtc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_webrtc_webrtc_proto_goTypes,
		DependencyIndexes: file_proto_webrtc_webrtc_proto_depIdxs,
		MessageInfos:      file_proto_webrtc_webrtc_proto_msgTypes,
	}.Build()
	File_proto_webrtc_webrtc_proto = out.File
	file_proto_webrtc_webrtc_proto_rawDesc = nil
	file_proto_webrtc_webrtc_proto_goTypes = nil
	file_proto_webrtc_webrtc_proto_depIdxs = nil
}
