CREATE ROLE users LOGIN PASSWORD 'users' NOINHERIT CREATEDB;

CREATE SCHEMA users AUTHORIZATION users;

GRANT USAGE ON SCHEMA users TO PUBLIC;

CREATE ROLE keycloak LOGIN PASSWORD 'keycloak' NOINHERIT CREATEDB;

CREATE SCHEMA keycloak AUTHORIZATION keycloak;

GRANT USAGE ON SCHEMA keycloak TO PUBLIC;