redis:
  port: 6379
  host: localhost
  password: ${REDIS_PASSWORD|}
  ttl: 7200

zeebe:
  port: 26500
  host: localhost

bpmn:
  src-folder: "../bp/bpmn/"

keycloak:
  url: "http://localhost:8086"
  admin-username: admin
  admin-password: ${KK_ADMIN_PASSWORD|admin}
  client-id: app
  client-secret: "d6dbae97-8570-4758-a081-9077b7899a7d"
  client-realm: prototype

mattermost:
  url: "http://localhost:8065"
  ws: "ws://localhost:8065"
  admin-username: admin
  admin-password: ${MM_ADMIN_PASSWORD|admin}
  admin-access-token: ${MM_BOT_ACCESS_TOKEN|oj9hp7iqyfrztxj9qah3u8n8we}
  team: rgs
  default-password: ${MM_DEFAULT_PASSWORD|12345}
  bot-username: bot.rgs
  bot-access-token: ${MM_BOT_ACCESS_TOKEN|jg88x5sb63yk8ng6kcfkb37iho}

http:
  host: localhost
  port: 8000
  ws-host: localhost
  ws-port: 8001
  tls:
    cert: ""
    key: ""

es:
  url: "http://localhost:9200"
  trace: false

nats:
  url: "nats://127.0.0.1:4222"
  clusterId: "test-cluster"

etcd:
  hosts:
    - "localhost:2379"

webrtc:

  signal:
    host: localhost
    port: 8002

# https://github.com/pion/ion-sfu/blob/master/config.toml
  pion:
    sfu:
      ballast: 0
      withstats: false
    router:
      maxbandwidth: 1500
      maxpackettrack: 500
      audiolevelthreshold: 40
      audiolevelinterval: 1000
      audiolevelfilter: 20
      simulcast:
        bestqualityfirst: true
        enabletemporallayer: false
    webrtc:
      iceportrange:
        - 5000
        - 5200
#      iceservers:
#        - urls:
#            - "stun:stun.stunprotocol.org:3478"
#        - urls:
#            - "turn:turn.awsome.org:3478"
#              username: "awsome"
#              credential: "awsome"
      sdpsemantics: "unified-plan"
      mdns: true
    turn:
      enabled: false
      realm: "ion"
      address: "0.0.0.0:3478"
      auth:
        credentials: "pion=ion,pion2=ion2"
    log:
      level: trace

  avp:
    samplebuilder:
      audiomaxlate: 100
      videomaxlate: 200
    webrtc:
      plicycle: 1000
    log:
      level: trace

  recording:
    file:
      enabled: true
      path: "/home/mikhailb/work/adacta/rgs-med/dev/prototype/recording/"

services:
  api:
    log:
      level: trace
    cluster:
      size: 1
  chat:
    database:
      dbname: mattermost
      user: chat
      password: ${DB_CHAT_PASSWORD|chat}
      port: 5432
      # read-write host
      host-rw: localhost
      # read-only host
      host-ro: localhost
      mig-src: "../chat/db/migrations"
    grpc:
      port: 51053
      host: localhost
    log:
      level: trace
    cluster:
      size: 1
  users:
    database:
      dbname: mattermost
      user: users
      password: ${DB_USERS_PASSWORD|users}
      port: 5432
      # read-write host
      host-rw: localhost
      # read-only host
      host-ro: localhost
      mig-src: "../users/db/migrations"
    grpc:
      port: 51051
      host: localhost
    log:
      level: trace
    cluster:
      size: 1
  tasks:
    database:
      dbname: mattermost
      user: tasks
      password: ${DB_TASKS_PASSWORD|tasks}
      port: 5432
      # read-write host
      host-rw: localhost
      # read-only host
      host-ro: localhost
      mig-src: "../tasks/db/migrations"
    grpc:
      port: 51052
      host: localhost
    log:
      level: trace
    cluster:
      size: 1
  services:
    database:
      dbname: mattermost
      user: services
      password: ${DB_SERVICES_PASSWORD|services}
      port: 5432
      # read-write host
      host-rw: localhost
      # read-only host
      host-ro: localhost
      mig-src: "../services/db/migrations"
    grpc:
      port: 51054
      host: localhost
    log:
      level: trace
    cluster:
      size: 1
  bp:
    grpc:
      port: 51055
      host: localhost
    log:
      level: trace
    cluster:
      size: 1
  cfg:
    grpc:
      port: 51056
      host: localhost
    log:
      level: trace
    cluster:
      size: 1
  sessions:
    grpc:
      port: 51057
      host: localhost
    database:
      dbname: mattermost
      user: sessions
      password: ${DB_SERVICES_PASSWORD|sessions}
      port: 5432
      # read-write host
      host-rw: localhost
      # read-only host
      host-ro: localhost
      mig-src: "../sessions/db/migrations"
    log:
      level: trace
    cluster:
      size: 1
  webrtc:
    grpc:
      port: 51058
      host: localhost
    database:
      dbname: mattermost
      user: webrtc
      password: ${DB_SERVICES_PASSWORD|webrtc}
      port: 5432
      # read-write host
      host-rw: localhost
      # read-only host
      host-ro: localhost
      mig-src: "../webrtc/db/migrations"
    log:
      level: debug
    cluster:
      size: 1
