apiVersion: v1
kind: Service
metadata:
  name: config
  labels:
    app: config
    group: config
spec:
  ports:
    - port: 51056
      name: grpc
      protocol: TCP
      targetPort: 51056
  selector:
    app: config
  sessionAffinity: None
  type: ClusterIP